---
- name: Setup Application on Debian
  hosts: db_and_web_server_1, db_and_web_server_2
  become: yes

  tasks:
    - name: Download MySQL tarball bundle
      get_url:
        url: "https://dev.mysql.com/get/mysql-apt-config_0.8.17-1_all.deb"
        dest: "/tmp/mysql-apt-config.deb"

    - name: Install MySQL APT configuration
      apt:
        deb: "/tmp/mysql-apt-config.deb"
        update_cache: yes

    - name: Install libaio1 library
      apt:
        name: libaio1
        state: present

    - name: Preconfigure MySQL server package
      shell: "sudo dpkg-preconfigure mysql-server"
      args:
        chdir: "/var/cache/debconf"
      become: yes

    - name: Install MySQL packages
      apt:
        deb: "/tmp/mysql-server_MVER-DVER_CPU.deb-bundle.tar/mysql-{common,community-client-plugins,community-client-core,community-client,client,community-server-core,community-server,server}_*.deb"
        state: present

    - name: Fix unmet dependencies (if any)
      apt:
        name: "*"
        state: present
      when: "'unmet dependencies' in dpkg_output.stdout"
      register: dpkg_output