- name: Deploy a web application
  hosts: db_and_web_servers
  tasks:
    - name: Install all required dependencies
      apt: name={{ item }} state=installed
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip