---
- name: Setup Application on Debian
  hosts: db_and_web_servers
  become: yes

  vars_files:
    - /group_vars/db_and_web_servers.yml

  tasks:
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv
        - python3-mysqldb

    #- include_tasks: tasks/deploy_db.yml
    - include_tasks: tasks/deploy_web.yml
