---
- name: Install and Secure MySQL Server
  hosts: db_and_web_server_1, db_and_web_server_2
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install gnupg
      apt:
        name: gnupg
        state: present

    - name: Download mysql-apt-config package
      get_url:
        url: "https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb"
        dest: "/home/vagrant/mysql-apt-config_0.8.22-1_all.deb"

    - name: Install mysql-apt-config package
      command: "dpkg -i /home/vagrant/mysql-apt-config_0.8.22-1_all.deb"
      become: yes

    - name: Update apt cache after adding MySQL repository
      apt:
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
      become: yes

    - name: Run mysql_secure_installation
      expect:
        command: mysql_secure_installation
        responses:
          'Enter password for user root:': "{{ your_root_password }}"
          'Press y\|Y for Yes, any other key for No': 'Y'
          'Please enter 0 = LOW, 1 = MEDIUM and 2 = STRONG': '2'  # Adjust as needed
          'Change the password for root \? \(\(Press y\|Y for Yes, any other key for No\)': '\n'  # Skip password change
          'Remove anonymous users\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Disallow root login remotely\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Remove test database and access to it\? \(Press y\|Y for Yes, any other key for No\)': 'Y'
          'Reload privilege tables now\? \(Press y\|Y for Yes, any other key for No\)': 'Y'

  vars:
    your_root_password: "root"  # Set your desired MySQL root password
