# This playbook requires privilege escalation to be set. Please
# refer the ansible.cfg in current working directory for privilege_escalation
# configuration.

- name: Deploy a web application
  hosts: db_and_web_server_1,db_and_web_server_2
  become: yes

  vars:
    mysql_root_password: root
    mysql_db_name: employee_db
    mysql_user: root
    mysql_user_password: root

  tasks:
    - name: Install all required dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "python3"
        - "python3-pip"
        - "python3-venv"
        - "python3-dev"
        - "python3-mysqldb"

    - name: Download MySQL APT Repository Key
      get_url:
        url: https://repo.mysql.com/RPM-GPG-KEY-mysql
        dest: /tmp/RPM-GPG-KEY-mysql
        mode: 0644

    - name: Add MySQL APT Repository Key
      command: apt-key add /tmp/RPM-GPG-KEY-mysql
      become: yes

    - name: Add MySQL APT Repository
      apt_repository:
        repo: deb http://repo.mysql.com/apt/debian/ buster mysql-8.0
        state: present

    - name: Update APT Package Cache
      apt:
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Secure MySQL Installation
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: "{{ item }}"
        priv: "*.*:ALL,GRANT"
        state: present
      with_items:
        - localhost
        - 127.0.0.1
        - ::1

    - name: Create MySQL Database
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Grant All Privileges to MySQL User
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: '*.*:ALL'
        host: localhost
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
        update_password: always

    - name: Install required Python libraries
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - "flask"
        - "Flask-MySQLdb"

    - name: Copy source code
      copy:
        src: app.py
        dest: /opt/app.py

    - name: Start web server
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &