---
- name: Setup Application on Debian
  hosts: db_and_web_server_1, db_and_web_server_2
  become: yes

  vars:
    db_name: employee_db
    db_user: db_user
    db_password: Passw0rd

  tasks:
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv

    - name: Install and Configure Database
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - default-mysql-server
        - default-mysql-client

    - name: Start Database Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create Application DB User
      mysql_user: name={{ db_user }} password={{ db_password }} priv='*.*:ALL' host='%' state='present'

    - name: Create Application Database
      mysql_db: name={{ db_name }} state=present

    - name: Install Python Flask dependency
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-flask
        - flask-mysql


    # - name: Configure and start Web Server
    #   command: "FLASK_APP=app.py flask run --host=0.0.0.0"
