---
- name: Setup Application on Debian
  hosts: db_and_web_server_1, db_and_web_server_2
  become: yes

  tasks:
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - default-libmysqlclient-dev

    - name: Install and Configure Database
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - default-mysql-server
        - default-mysql-client

    - name: Start Database Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database and users
      mysql_user:
        name: db_user
        password: Passw0rd
        host: "%"
        priv: "*.*:ALL,GRANT"
        become_user: mysql
        become: yes

    - name: Create employee_db database
      mysql_db:
        name: employee_db
        become_user: mysql
        become: yes

    - name: Insert test data into employee_db
      mysql_query:
        query: "INSERT INTO employees VALUES ('JOHN')"
        db: employee_db
        become_user: mysql
        become: yes

    - name: Install Python Flask dependency
      pip:
        name: "{{ item }}"
        executable: pip3
      loop:
        - flask
        - Flask-MySQLdb

    - name: Configure and start Web Server
      command: "FLASK_APP=app.py flask run --host=0.0.0.0"
